//! The label space the recognisers predict over.
//!
//! These are the fruit/vegetable categories used by the app. They are kept in
//! one place so that once the real CNN / KNN / VLM models are trained, the
//! rest of the app keeps working unchanged. If your trained model uses a
//! different label set, this is the single list to edit.

pub const CATEGORIES: &[&str] = &[
    "Almonds",
    "Apple",
    "Apple Braeburn",
    "Apple Crimson Snow",
    "Apple Golden",
    "Apple Granny Smith",
    "Apple Pink Lady",
    "Apple Red",
    "Apple Red Delicious",
    "Apple Red Yellow",
    "Apricot",
    "Avocado",
    "Avocado Black",
    "Avocado Green",
    "Banana",
    "Banana Lady Finger",
    "Banana Red",
    "Bean pod",
    "Beetroot",
    "Blackberry",
    "BlackBerry",
    "Blueberry",
    "Cabbage red",
    "Cabbage white",
    "Cactus fruit",
    "Cactus fruit green",
    "Cactus fruit red",
    "Caju seed",
    "Cantaloupe",
    "Carambola",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Cherimoya",
    "Cherry",
    "Cherry Rainier",
    "Cherry Sour",
    "Cherry Wax",
    "Cherry Wax Black",
    "Cherry Wax Red",
    "Cherry Wax Yellow",
    "Chestnut",
    "Clementine",
    "Cocos",
    "Corn",
    "Corn Husk",
    "Cucumber",
    "Dates",
    "Eggplant",
    "Eggplant long",
    "Fig",
    "Ginger",
    "Ginger Root",
    "Gooseberry",
    "Granadilla",
    "Grape",
    "Grape Blue",
    "Grape Pink",
    "Grape pink",
    "Grape White",
    "Grapefruit Pink",
    "Grapefruit White",
    "Guava",
    "Hazelnut",
    "Huckleberry",
    "Kaki",
    "Kiwi",
    "Kohlrabi",
    "Kumquats",
    "Lemon",
    "Lemon Meyer",
    "Limes",
    "Lychee",
    "Mandarine",
    "Mango",
    "Mango Red",
    "Mangostan",
    "Maracuja",
    "Melon Piel de Sapo",
    "Mulberry",
    "Nectarine",
    "Nectarine Flat",
    "Nut Forest",
    "Nut Pecan",
    "Onion",
    "Onion Red",
    "Onion White",
    "Orange",
    "orange",
    "Orange peeled",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Peach Flat",
    "Peanut shell 1x",
    "Pear Abate",
    "Pear Forelle",
    "Pear Kaiser",
    "Pear Monster",
    "Pear Red",
    "Pear Stone",
    "Pear Williams",
    "Pepino",
    "Pepper",
    "Pepper Green",
    "Pepper Orange",
    "Pepper Red",
    "Pepper Yellow",
    "Physalis",
    "Physalis with Husk",
    "Pineapple",
    "Pineapple Mini",
    "Pistachio",
    "Pitahaya Red",
    "Plum",
    "Pomegranate",
    "Pomelo Sweetie",
    "Potato Red",
    "Potato Sweet",
    "Potato White",
    "Quince",
    "Rambutan",
    "Raspberry",
    "Redcurrant",
    "Salak",
    "Strawberry",
    "Strawberry Wedge",
    "Tamarillo",
    "Tangelo",
    "Tomato",
    "Tomato Cherry Maroon",
    "Tomato Cherry Orange",
    "Tomato Cherry Red",
    "Tomato Cherry Yellow",
    "Tomato Heart",
    "Tomato Maroon",
    "Tomato Yellow",
    "Walnut",
    "Watermelon",
    "Zucchini",
    "Zucchini dark",
    "Zucchini Green",
];
